# -*- coding: utf-8 -*-
"""UAS_FARIS NAUFAL ASLAM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pOYlx7t2lhPoPVIaPWEv3zhgYIMWd_ca
"""

''2 !pip install texttable
from texttable import Texttable
import sys
print("\nSELAMAT DATANG DI PENAMBAHAN KONTAK\n")
namaanda = input("Masukan nama anda: ")
print("Apakah Anda ingin menambahkan kontak ?\n")
print("1. Ya \t 2. Tidak")

a = int(input("Pilih: "))
if a ==2:
  sys.exit()

y= int(input("Masukan jumlah teman yang akan ditambah "))
x=0
table = Texttable()
namateman = []
Hoby = []
NO = []
Alamat = []

while x<y:
   print("Masukan Data Teman")
   namateman.append(input("nama: "))
   Hoby.append(input("hoby: "))
   NO.append(input("nomer: "))
   Alamat.append(input("alamat: "))
   x+=1

for n in range (y):
    table.add_rows([['Nomor','Nama','Hoby','Nomor Telepon','Alamat'],[n+1,namateman[n],Hoby[n],NO[n],Alamat[n]]])

print(table.draw())
print("Terima Kasih")

